version: "3"
services:
  db:
    container_name: auth-and-privilege
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dbo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3336:3306'
    expose:
      - '3336'
